# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'PinMusubi' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PinMusubi
  pod 'RealmSwift', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', submodules: true
  pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', submodules: true
  pod 'LicensePlist'
  pod 'SwiftLint'
  pod 'FloatingPanel'

  target 'PinMusubiTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RealmSwift', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', submodules: true
    pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', submodules: true
    pod 'SwiftLint'
    pod 'FloatingPanel'
  end

  target 'PinMusubiUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RealmSwift', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', submodules: true
    pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', submodules: true
    pod 'SwiftLint'
    pod 'FloatingPanel'
  end

end
