# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'PinMusubi' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PinMusubi
  pod 'RealmSwift'
  pod 'LicensePlist'
  pod 'SwiftLint'

  target 'PinMusubiTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RealmSwift'
    pod 'SwiftLint'
  end

  target 'PinMusubiUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RealmSwift'
    pod 'SwiftLint'
  end

end
